service: app

provider:
    name: aws
    region: eu-west-1
    runtime: provided.al2

custom:
    bref:
        separateVendor: false

plugins:
    - serverless-iam-roles-per-function
    - ./vendor/bref/bref

functions:
    addBook:
        handler: ./src/Events/create/index.php
        description: 'Add a new book'
        layers:
            - ${bref:layer.php-81}
        iamRoleStatements:
            - Effect: 'Allow'
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource: 'arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/book'

    getBook:
        handler: ./src/Events/read/index.php
        description: 'Get a specific book'
        layers:
            - ${bref:layer.php-81}
        iamRoleStatements:
            - Effect: 'Allow'
              Action:
                - dynamodb:GetItem
              Resource: 'arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/book'

    deleteBook:
        handler: ./src/Events/delete/index.php
        description: 'Delete a book'
        layers:
            - ${bref:layer.php-81}
        iamRoleStatements:
            - Effect: 'Allow'
              Action:
                - dynamodb:DeleteItem
              Resource: 'arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/book'

# Exclude files from deployment
package:
    patterns:
        - '!tests/**'
        - '!node_modules/**'

resources:
  Resources:
    BookTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'book'
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
