service: app

provider:
    name: aws
    region: eu-west-1
    runtime: provided.al2

plugins:
    - ./vendor/bref/bref

custom:
    bref:
        separateVendor: true

functions:
    addBook:
        handler: ./src/Events/create/index.php
        description: ''
        layers:
            - ${bref:layer.php-81}

    getBook:
        handler: ./src/Events/read/index.php
        description: ''
        layers:
            - ${bref:layer.php-81}

    deleteBook:
        handler: ./src/Events/delete/index.php
        description: ''
        layers:
            - ${bref:layer.php-81}

# Exclude files from deployment
package:
    patterns:
        - '!tests/**'
