
services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      App\BusinessRules\Gateways\BookGateway $bookGateway: '@App\Repositories\BookRepository'

  App\Repositories\BookRepository: ~

  App\BusinessRules\UseCases\AddBook\AddBook:
    public: true

  App\BusinessRules\UseCases\GetBook\GetBook:
    public: true

  App\BusinessRules\UseCases\RemoveBook\RemoveBook:
    public: true
